openapi: 3.0.0
info:
  title: VK API
  description: The VK API description
  version: "1.0"
  contact: {}

paths:
  "/users":
    get:
      operationId: users_list
      tags:
        - users
      summary: Get users list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/UserModel"
  "/users/{userId}/friends":
    get:
      operationId: users_friends_list
      tags:
        - users
      summary: Get users friends list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/UserModel"
  "/users/{userId}":
    get:
      operationId: user_info
      tags:
        - users
      summary: Get user info
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserModel"

  "/feeds":
    get:
      operationId: feeds_list
      tags:
        - feeds
      summary: Get feeds list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          allOf:
                            - $ref: "#/components/schemas/FeedModel"
                            - properties:
                                user:
                                  $ref: "#/components/schemas/UserModel"
    post:
      operationId: feeds_create
      tags:
        - feeds
      summary: Create feed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                uploadsIds:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  "/feeds/user/{userId}":
    get:
      operationId: users_feeds_list
      tags:
        - feeds
      summary: Get users feeds list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/UserModel"
  "/feeds/my":
    get:
      operationId: my_feeds_list
      tags:
        - feeds
      summary: Get my feeds list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/UserModel"

  "/chats":
    get:
      operationId: chats_list
      tags:
        - chats
      summary: Get chats list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          properties:
                            id:
                              type: string
                            user:
                              $ref: "#/components/schemas/UserModel"
                            lastMessage:
                              $ref: "#/components/schemas/MessageModel"
  "/chats/{chatId}":
    get:
      operationId: chat_info
      tags:
        - chats
      summary: Get chat info
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                properties:
                  user:
                    $ref: "#/components/schemas/UserModel"
  "/chats/{chatId}/messages":
    get:
      operationId: chats_messages_list
      tags:
        - chats
      summary: Get chat messages list
      parameters:
        - $ref: "#/components/parameters/NextCursor"
        - $ref: "#/components/parameters/Size"
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pagination"
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: "#/components/schemas/MessageModel"
    post:
      operationId: message_create
      tags:
        - chats
      summary: Create chat message
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string

  "/uploads":
    post:
      operationId: upload_create
      tags:
        - uploads
      summary: Create upload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
  "/uploads/{uploadId}/file":
    get:
      operationId: uploads_file
      tags:
        - uploads
      summary: Get uploaded file
      parameters:
        - name: uploadId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/file:
              schema:
                type: string
                format: binary

tags:
  - name: users
    description: "Users"
  - name: feeds
    description: "Feeds"
  - name: chats
    description: "Chats"
  - name: uploads
    description: "Uploads"

components:
  parameters:
    NextCursor:
      name: nextCursor
      required: false
      in: query
      schema:
        type: string
    Size:
      name: size
      required: false
      in: query
      schema:
        type: number

  schemas:
    Pagination:
      type: object
      properties:
        nextCursor:
          type: string
        size:
          type: number

    UserModel:
      type: object
      properties:
        id:
          type: string
        fullName:
          type: string
          example: Ivanov Ivan
      required:
        - id
        - fullName

    FeedModel:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
          example: News
        createdAt:
          type: string
          example: "YYYY-MM-DDTHH:mm:ss"
      required:
        - id
        - content
        - createdAt

    MessageModel:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        content:
          type: string
          example: News
        createdAt:
          type: string
          example: "YYYY-MM-DDTHH:mm:ss"
      required:
        - id
        - userId
        - content
        - createdAt
