CREATE TABLE "cities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" String NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" String NOT NULL,
  "description" String NOT NULL,
  "city_id" Int NOT NULL,
  "photo_id" Int
);

CREATE TABLE "user_interests" (
  "user_id" Int NOT NULL,
  "title" String NOT NULL
);

CREATE TABLE "user_friends" (
  "user_id" Int NOT NULL,
  "friend_user_id" Int NOT NULL
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" Int NOT NULL,
  "content" String NOT NULL,
  "created_at" Date NOT NULL
);

CREATE TABLE "uploads" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "path" String NOT NULL
);

CREATE TABLE "post_upload" (
  "post_id" Int NOT NULL,
  "upload_id" Int NOT NULL
);

CREATE INDEX ON "users" USING HASH ("city_id");

CREATE INDEX ON "user_interests" USING HASH ("title");

CREATE INDEX ON "user_interests" USING HASH ("user_id");

CREATE INDEX ON "user_friends" USING HASH ("user_id");

CREATE INDEX ON "user_friends" USING HASH ("friend_user_id");

CREATE INDEX ON "posts" USING HASH ("user_id");

CREATE INDEX ON "posts" USING BTREE ("created_at");

CREATE INDEX ON "post_upload" USING HASH ("post_id");

ALTER TABLE "cities" ADD FOREIGN KEY ("id") REFERENCES "users" ("id");

ALTER TABLE "uploads" ADD FOREIGN KEY ("id") REFERENCES "users" ("photo_id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_friends" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_friends" ADD FOREIGN KEY ("friend_user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "post_upload" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "uploads" ADD FOREIGN KEY ("id") REFERENCES "post_upload" ("upload_id");
