CREATE TYPE "ChatType" AS ENUM (
  'private',
  'public'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" String NOT NULL,
  "photo_id" Int
);

CREATE TABLE "uploads" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "path" String NOT NULL
);

CREATE TABLE "chats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" ChatType NOT NULL,
  "created_at" Date NOT NULL
);

CREATE TABLE "chat_user" (
  "chat_id" Int NOT NULL,
  "user_id" Int NOT NULL
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" Int NOT NULL,
  "user_id" Int NOT NULL,
  "content" String NOT NULL,
  "created_at" Date NOT NULL
);

CREATE TABLE "chat_last_readed" (
  "chat_id" Int NOT NULL,
  "user_id" Int NOT NULL,
  "message_id" Int NOT NULL
);

CREATE INDEX ON "chat_user" USING HASH ("user_id");

CREATE INDEX ON "messages" USING HASH ("chat_id", "user_id");

CREATE INDEX ON "chat_last_readed" USING HASH ("chat_id", "user_id");

ALTER TABLE "uploads" ADD FOREIGN KEY ("id") REFERENCES "users" ("photo_id");

ALTER TABLE "chat_user" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

CREATE TABLE "users_chat_user" (
  "users_id" Int,
  "chat_user_user_id" Int,
  PRIMARY KEY ("users_id", "chat_user_user_id")
);

ALTER TABLE "users_chat_user" ADD FOREIGN KEY ("users_id") REFERENCES "users" ("id");

ALTER TABLE "users_chat_user" ADD FOREIGN KEY ("chat_user_user_id") REFERENCES "chat_user" ("user_id");


ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");

ALTER TABLE "chat_user" ADD FOREIGN KEY ("user_id") REFERENCES "messages" ("user_id");

ALTER TABLE "chat_user" ADD FOREIGN KEY ("chat_id", "user_id") REFERENCES "chat_last_readed" ("chat_id", "user_id");

ALTER TABLE "chat_last_readed" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");
