CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" String NOT NULL,
  "photo_id" Int
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" Int NOT NULL,
  "content" String NOT NULL,
  "created_at" Date NOT NULL
);

CREATE TABLE "uploads" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "path" String NOT NULL
);

CREATE TABLE "post_upload" (
  "post_id" Int NOT NULL,
  "upload_id" Int NOT NULL
);

CREATE INDEX ON "posts" USING HASH ("user_id");

CREATE INDEX ON "posts" USING BTREE ("created_at");

CREATE INDEX ON "post_upload" USING HASH ("post_id");

ALTER TABLE "uploads" ADD FOREIGN KEY ("id") REFERENCES "users" ("photo_id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "post_upload" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "uploads" ADD FOREIGN KEY ("id") REFERENCES "post_upload" ("upload_id");
